spring.application.name=springboot-error

# Configuración para personalizar el error 404 y evitar que Spring Boot lo haga.
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false